name: osta_app
description: "A new Osta Application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

#-------------------- PACKAGES --------------------#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Change Language
  flutter_localizations:
    sdk: flutter

  # Utility Package
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
#  permission_handler: ^11.1.0
#  grouped_checkbox: ^2.0.0

  # Icons
  iconsax: ^0.0.8

  # State Management
  flutter_bloc: ^8.1.3

  # Product Specific
  cached_network_image: ^3.3.0

  # Responsive Ui
  flutter_screenutil: ^5.9.0

  # Make Animation When Navigate
  page_transition: ^2.1.0

  # SVG Pictures
  flutter_svg: ^2.0.9

  # Custom Field On OTP
  pinput: ^3.0.1

  # Check to Internet
  internet_connection_checker: ^1.0.0+1

  #Flutter Rate
  flutter_rating_bar: ^4.0.1

  # flutter_timeline_calendar
  flutter_timeline_calendar: ^1.0.9
  flutter_time_picker_spinner: ^2.0.0

  # dotted Border
  dotted_border: ^2.1.0

  # Get Location => Map Services
  geolocator: ^10.1.0
  geocoding:
  google_maps_flutter: ^2.5.0
  maps_launcher: any

#-------------------- PACKAGES End --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  #-------------------- LOCAL ASSETS --------------------#
  assets:
    - assets/lang/
    - assets/icons/
    - assets/lotties/
    - assets/images/
    - assets/images/logos/
    - assets/images/animations/
    - assets/images/on_boarding_images/


  #-------------------- LOCAL FONTS --------------------#
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/ar/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/ar/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/ar/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/ar/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ar/Cairo-Bold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/en/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/en/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/en/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/en/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/en/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/en/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/en/Poppins-Bold.ttf
          weight: 800